name: agap_mobile_v01
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get: ^4.6.6
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0
  fl_chart: ^0.66.0
  image_picker: ^1.0.7
  animated_rating_stars: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4
  firebase_messaging: ^14.8.1
  firebase_storage: ^11.6.9
  flutter_device_type: ^0.4.0
  lottie: ^3.1.0
  pinput: ^4.0.0
  firebase_app_check: ^0.2.2+1
  google_geocoding_api: ^1.5.0
  google_places_flutter: ^2.0.8
  google_maps_flutter: ^2.6.0
  url_launcher: ^6.2.5
  local_auth: ^2.2.0
  loading_animation_widget: ^1.2.1
  cloud_functions: ^4.7.1
  google_sign_in: ^6.2.1
  calendar_date_picker2: ^0.5.6
  intl: ^0.19.0
  flutter_email_sender: ^6.0.3
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/square_logo_white.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/square_logo_white.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/square_logo_white.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/square_logo_white.png"